# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 1111   # HTTP (Tomcat) port
  
  
zuul:
  prefix: /api  #service will be mapped under api URI
  routes:
    employee-service:
      path: /employee-service/**
      url: http://localhost:3333
    department-service:
      path: /department-service/**
      url: http://localhost:4444